### ISSUE TITLE
New image is not filling the canvas.

### ISSUE THREAD

**Issue by safaldas-neoito** [rachana1792/image-palette#1]
<img width="1248" alt="Screenshot 2023-07-10 at 3 58 20 PM" src="https://github.com/rachana1792/image-palette/assets/50335853/7152bab3-e682-4f52-999a-ddc4dbe158bf">
See the example above. I added a new image and it is only in a small part and not covering entire canvas

**Comment by rachana1792** [comment]
done and pushed
